/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    AutoImportDemo: typeof import('./../components/AutoImportDemo.vue')['default']
    Captcha: typeof import('./../components/login/captcha/index.vue')['default']
    Default: typeof import('./../layouts/default/index.vue')['default']
    EnvInfo: typeof import('./../components/EnvInfo.vue')['default']
    FeatureList: typeof import('./../components/login/feature-list/index.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    LocaleDemo: typeof import('./../components/LocaleDemo.vue')['default']
    LoginDebug: typeof import('./../components/LoginDebug.vue')['default']
    LoginForm: typeof import('./../components/login/login-form/index.vue')['default']
    LoginTest: typeof import('./../components/LoginTest.vue')['default']
    MockDemo: typeof import('./../components/MockDemo.vue')['default']
    PermissionDemo: typeof import('./../components/PermissionDemo.vue')['default']
    RegisterForm: typeof import('./../components/login/register-form/index.vue')['default']
    RequestDemo: typeof import('./../components/RequestDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./../components/login/settings-panel/index.vue')['default']
    StoreDemo: typeof import('./../components/StoreDemo.vue')['default']
    StyleDemo: typeof import('./../components/StyleDemo.vue')['default']
    UtilsDemo: typeof import('./../components/UtilsDemo.vue')['default']
  }
}
